# DO NOT EDIT - generated by the root OpenTofu configuration (main.tf).
#
# This is the original project's copy of the same schema every self-service
# project's environments/*.tfvars file uses - see environments/demo-project.tfvars
# for a hand-written example, and iacm/variables.tf for the full schema.
#
# region, environment_name and manage_environment are deliberately not here:
# they're set directly on this project's workspace instead (harness.tf), the
# same way the environment-creation pipeline sets them on every self-service
# workspace it creates - a value living in this file would apply to every
# workspace that links it, which is only ever this one, but keeping the two
# mechanisms identical means there is exactly one way this works, not two.
#
# Regenerated on every root apply. Change the values in the root variables.tf
# instead of editing this file - the next apply overwrites it.

project_name = "lambda-service-poc"

harness = {
  org_id              = "default"
  project_id          = "lambda_service_poc"
  github_connector_id = "github_connector"
  github_branch       = "main"
  aws_connector_id    = "aws_lambda_connector"
}

lambdas = {
  lambda_service = {
    runtime               = "nodejs20.x"
    handler               = "index.handler"
    timeout               = 10
    memory_size           = 128
    execution_role_arn    = "arn:aws:iam::915632791698:role/lambda-service-poc-exec-role"
    architecture          = "x86_64"
    publish_version       = true
    environment_variables = {}

    artifact_by_region = {
      "us-east-1" = {
        bucket = "lambda-service-poc-artifacts-915632791698"
        key    = "lambda-service-poc/lambda.zip"
      }
    }

    function_definition_path = "harness/function-definition.json"

    # Pins this project's existing identifiers so migrating onto the shared
    # multi-lambda schema does not rename or recreate anything.
    function_name              = "lambda-service-poc"
    service_identifier         = "lambda_service"
    artifact_source_identifier = "lambda_artifact"
  }
}

tags = {
  "Application" = "lambda-service-poc"
  "Environment" = "dev"
  "ManagedBy"   = "OpenTofu"
  "Owner"       = "platform-engineering"
  "Repository"  = "kartikkaushik27/lambda-service-setup"
}
