# DO NOT EDIT - generated by the root OpenTofu configuration (generated.tf).
#
# OpenTofu loads any *.auto.tfvars file in its working directory, so this is
# how the IACM stage receives its non-secret inputs. Editing it by hand is
# pointless: the next root apply overwrites it. Change the values in the root
# variables.tf (or a .tfvars file passed to it) instead.
#
# Credentials are deliberately absent - they reach the run as environment
# variables from the Harness credentials variable set.

aws_region = "us-east-1"

function = {
  name                  = "lambda-service-poc"
  runtime               = "nodejs20.x"
  handler               = "index.handler"
  timeout               = 10
  memory_size           = 128
  architecture          = "x86_64"
  publish_version       = true
  execution_role_arn    = "arn:aws:iam::915632791698:role/lambda-service-poc-exec-role"
  environment_variables = {}
}

artifact = {
  # Stable key the function itself is deployed from.
  bucket = "lambda-service-poc-artifacts-915632791698"
  key    = "lambda-service-poc/lambda.zip"

  # What the Harness service deploys. "<+input>" leaves it a runtime input the
  # pipeline fills in with the per-build key its CI stage published.
  service_file_path = "<+input>"
}

harness = {
  org_id                     = "default"
  project_id                 = "lambda_service_poc"
  aws_connector_id           = "aws_lambda_connector"
  github_connector_id        = "github_connector"
  github_branch              = "main"
  function_definition_path   = "harness/function-definition.json"
  service_identifier         = "lambda_service"
  artifact_source_identifier = "awslambdaartifact"
}

tags = {
  "Application" = "lambda-service-poc"
  "Environment" = "dev"
  "ManagedBy" = "OpenTofu"
  "Owner" = "platform-engineering"
  "Repository" = "kartikkaushik27/lambda-service-setup"
}
