# DO NOT EDIT - generated by the root OpenTofu configuration (main.tf).
#
# OpenTofu loads any *.auto.tfvars file in its working directory, so this is how
# the IACM stage receives its non-secret inputs. Editing it by hand is
# pointless: the next root apply overwrites it. Change the values in the root
# variables.tf instead.
#
# Credentials are deliberately absent - they reach the run as environment
# variables from the Harness credentials variable set.

aws_region = "us-east-1"

function = {
  name                  = "lambda-service-poc"
  runtime               = "nodejs20.x"
  handler               = "index.handler"
  timeout               = 10
  memory_size           = 128
  architecture          = "x86_64"
  publish_version       = true
  execution_role_arn    = "arn:aws:iam::915632791698:role/lambda-service-poc-exec-role"
  environment_variables = {}
}

# Only the function itself is built from a fixed location. The Harness service
# takes its artifact location as runtime inputs, supplied per execution by
# whichever stage published the package.
artifact = {
  bucket = "lambda-service-poc-artifacts-915632791698"
  key    = "lambda-service-poc/lambda.zip"
}

harness = {
  org_id                     = "default"
  project_id                 = "lambda_service_poc"
  github_connector_id        = "github_connector"
  github_branch              = "main"
  function_definition_path   = "harness/function-definition.json"
  service_identifier         = "lambda_service"
  artifact_source_identifier = "lambda_artifact"
}

tags = {
  "Application" = "lambda-service-poc"
  "Environment" = "dev"
  "ManagedBy" = "OpenTofu"
  "Owner" = "platform-engineering"
  "Repository" = "kartikkaushik27/lambda-service-setup"
}
