# DO NOT EDIT - generated by the root OpenTofu configuration (main.tf).
#
# This is the original project's copy of the same schema every self-service
# project uses (see environments/*.tfvars) - the difference is this one is
# rendered and committed by the root apply instead of written by hand, and it
# sets manage_environment = false because the root config already created
# this project's environment/infrastructure definition directly (harness.tf).
#
# OpenTofu loads any *.auto.tfvars file in its working directory, so this is
# how the IACM stage receives its non-secret inputs. Editing it by hand is
# pointless: the next root apply overwrites it. Change the values in the root
# variables.tf instead.
#
# Credentials are deliberately absent - they reach the run as environment
# variables from the Harness credentials variable set.

project_name       = "lambda-service-poc"
region             = "us-east-1"
environment_name   = "dev"
manage_environment = false

harness = {
  org_id              = "default"
  project_id          = "lambda_service_poc"
  github_connector_id = "github_connector"
  github_branch       = "main"
  aws_connector_id    = "aws_lambda_connector"
}

lambdas = {
  lambda_service = {
    runtime                = "nodejs20.x"
    handler                = "index.handler"
    timeout                = 10
    memory_size            = 128
    execution_role_arn     = "arn:aws:iam::915632791698:role/lambda-service-poc-exec-role"
    architecture           = "x86_64"
    publish_version        = true
    environment_variables  = {}

    artifact = {
      bucket = "lambda-service-poc-artifacts-915632791698"
      key    = "lambda-service-poc/lambda.zip"
    }

    function_definition_path = "harness/function-definition.json"

    # Pins this project's existing identifiers so migrating onto the shared
    # multi-lambda schema does not rename or recreate anything.
    function_name              = "lambda-service-poc"
    service_identifier          = "lambda_service"
    artifact_source_identifier  = "lambda_artifact"
  }
}

tags = {
  "Application" = "lambda-service-poc"
  "Environment" = "dev"
  "ManagedBy"   = "OpenTofu"
  "Owner"       = "platform-engineering"
  "Repository"  = "kartikkaushik27/lambda-service-setup"
}
